name: Bug Report
description: Reportar um bug ou problema
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva claramente o problema encontrado
      placeholder: O que aconteceu?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Como podemos reproduzir o problema?
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que está acontecendo?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Outro
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Sistema Operacional
      placeholder: ex. Windows 11, macOS 13, Ubuntu 22.04

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Se aplicável, adicione screenshots
