name: Feature Request
description: Sugerir uma nova funcionalidade
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma melhoria! Por favor, preencha as informações abaixo.

  - type: textarea
    id: problem
    attributes:
      label: Problema ou Necessidade
      description: Qual problema esta feature resolveria?
      placeholder: Seria útil poder...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que isso funcionaria?
      placeholder: A aplicação deveria...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Você considerou outras soluções?

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante
